[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc = "0.8.25"  # 确保使用支持 cancun 的版本
evm_version = "istanbul"
bytecode_hash = "none"
cbor_metadata = false